            /* ============================================================
   STICKMAN DOMINION 3.1 - REFACTORED ENGINE & LOGIC
   ============================================================ */

            // --- CONFIGURATION ---
            const CONFIG = {
                WORLD_WIDTH: 4500,
                GROUND_Y: window.innerHeight - 180,
                GRAVITY: 0.5,
                EDGE_SCROLL_MARGIN: 50,
                EDGE_SCROLL_SPEED: 18,
            };

            const TEAMS = { PLAYER: 1, ENEMY: 2 };
            const RESOURCES = {
                START_GOLD: 150,
                START_IRON: 0,
                START_CRYSTAL: 0,
                MAX_MANA: 100,
                MANA_REGEN: 0.05,
            };

            // --- DEFINITIONS ---
            const SPELLS = {
                meteor: {
                    name: "Meteor Strike",
                    cost: 50,
                    radius: 150,
                    damage: 350,
                    color: "#f97316",
                    desc: "Calls down a devastating meteor.",
                },
                blizzard: {
                    name: "Blizzard",
                    cost: 40,
                    radius: 220,
                    duration: 300,
                    color: "#38bdf8",
                    desc: "Freezes enemies and deals DOT.",
                },
                heal: {
                    name: "Holy Light",
                    cost: 30,
                    radius: 200,
                    heal: 200,
                    color: "#fde047",
                    desc: "Instantly heals allied units and buildings in area.",
                },
                lightning: {
                    name: "Chain Lightning",
                    cost: 45,
                    chains: 4,
                    damage: 120,
                    color: "#38bdf8",
                    desc: "Arcs through up to 4 enemies, dealing decreasing damage.",
                },
            };

            const UNIT_TYPES = {
                militia: {
                    name: "Militia",
                    hp: 80,
                    dmg: 10,
                    range: 45,
                    speed: 2.2,
                    cooldown: 40,
                    cost: { g: 10 },
                    pop: 1,
                    armor: 0,
                    visual: "sword",
                },
                swordsman: {
                    name: "Swordsman",
                    hp: 150,
                    dmg: 18,
                    range: 50,
                    speed: 1.8,
                    cooldown: 45,
                    cost: { g: 25 },
                    pop: 1,
                    armor: 2,
                    visual: "sword_shield",
                },
                spearman: {
                    name: "Spearman",
                    hp: 120,
                    dmg: 22,
                    range: 75,
                    speed: 1.6,
                    cooldown: 50,
                    cost: { g: 30 },
                    pop: 1,
                    armor: 1,
                    visual: "spear",
                },
                archer: {
                    name: "Archer",
                    hp: 65,
                    dmg: 15,
                    range: 250,
                    speed: 1.4,
                    cooldown: 60,
                    cost: { g: 35 },
                    pop: 1,
                    armor: 0,
                    ranged: true,
                    projectile: "arrow",
                    visual: "bow",
                },
                crossbow: {
                    name: "Crossbowman",
                    hp: 80,
                    dmg: 35,
                    range: 280,
                    speed: 1.2,
                    cooldown: 90,
                    cost: { g: 50 },
                    pop: 1,
                    armor: 2,
                    ranged: true,
                    projectile: "bolt",
                    pierce: 3,
                    visual: "crossbow",
                },
                cleric: {
                    name: "Cleric",
                    hp: 90,
                    dmg: 6,
                    range: 140,
                    speed: 1.3,
                    cooldown: 80,
                    cost: { g: 60 },
                    pop: 1,
                    armor: 0,
                    heal: 40,
                    healRange: 180,
                    healCd: 90,
                    visual: "staff",
                },
                knight: {
                    name: "Knight",
                    hp: 280,
                    dmg: 32,
                    range: 55,
                    speed: 3.4,
                    cooldown: 55,
                    cost: { g: 80, i: 10 },
                    pop: 2,
                    armor: 5,
                    charge: true,
                    visual: "horse",
                },
                mage: {
                    name: "Mage",
                    hp: 75,
                    dmg: 50,
                    range: 220,
                    speed: 1.1,
                    cooldown: 100,
                    cost: { g: 100, c: 20 },
                    pop: 1,
                    armor: 0,
                    ranged: true,
                    projectile: "fireball",
                    aoe: 80,
                    visual: "mage",
                },
                catapult: {
                    name: "Catapult",
                    hp: 200,
                    dmg: 90,
                    range: 480,
                    speed: 0.7,
                    cooldown: 180,
                    cost: { g: 150, i: 30 },
                    pop: 3,
                    armor: 3,
                    ranged: true,
                    projectile: "rock",
                    aoe: 120,
                    siege: true,
                    visual: "catapult",
                },
                paladin: {
                    name: "Paladin",
                    hp: 320,
                    dmg: 28,
                    range: 52,
                    speed: 2.0,
                    cooldown: 60,
                    cost: { g: 120, c: 30 },
                    pop: 2,
                    armor: 6,
                    heal: 18,
                    healRange: 160,
                    healCd: 120,
                    visual: "sword_shield",
                },
            };

            // ─── PERMANENT PER-UNIT UPGRADES (META PROGRESSION) ──────────────
            // Persisted to localStorage. Each unit type can buy permanent ranks
            // in HP and DMG that apply to every copy of that unit, every game.
            const META_STATS = [
                {
                    key: "hp",
                    name: "Vitality",
                    icon: "❤",
                    per: 0.08, // +8% max HP per rank
                    color: "#ef4444",
                },
                {
                    key: "dmg",
                    name: "Power",
                    icon: "⚔",
                    per: 0.08, // +8% damage per rank
                    color: "#fbbf24",
                },
            ];
            const META_MAX_RANK = 5;
            // Valor cost for the NEXT rank (index = current rank).
            const META_COST = [30, 50, 80, 120, 180];

            const ENEMY_TYPES = {
                rabble: {
                    name: "Rabble",
                    hp: 50,
                    dmg: 8,
                    range: 45,
                    speed: 1.6,
                    cooldown: 50,
                    bounty: 5,
                    armor: 0,
                    scale: 0.9,
                    visual: "sword",
                },
                marauder: {
                    name: "Marauder",
                    hp: 110,
                    dmg: 15,
                    range: 50,
                    speed: 1.8,
                    cooldown: 55,
                    bounty: 12,
                    armor: 1,
                    scale: 1.0,
                    visual: "sword_shield",
                },
                berserker: {
                    name: "Berserker",
                    hp: 90,
                    dmg: 28,
                    range: 45,
                    speed: 3.0,
                    cooldown: 40,
                    bounty: 18,
                    armor: 0,
                    scale: 1.05,
                    color: "#ef4444",
                    visual: "dual",
                },
                shieldman: {
                    name: "Shieldman",
                    hp: 220,
                    dmg: 12,
                    range: 45,
                    speed: 1.1,
                    cooldown: 70,
                    bounty: 22,
                    armor: 6,
                    scale: 1.1,
                    color: "#60a5fa",
                    visual: "tower_shield",
                },
                archer: {
                    name: "Enemy Archer",
                    hp: 55,
                    dmg: 14,
                    range: 230,
                    speed: 1.3,
                    cooldown: 70,
                    bounty: 15,
                    armor: 0,
                    ranged: true,
                    projectile: "arrow",
                    scale: 0.95,
                    visual: "bow",
                },
                shaman: {
                    name: "Shaman",
                    hp: 100,
                    dmg: 10,
                    range: 130,
                    speed: 1.2,
                    cooldown: 90,
                    bounty: 35,
                    armor: 0,
                    heal: 30,
                    healRange: 160,
                    healCd: 100,
                    scale: 1.0,
                    color: "#34d399",
                    visual: "staff",
                },
                ogre: {
                    name: "Ogre",
                    hp: 550,
                    dmg: 45,
                    range: 65,
                    speed: 0.9,
                    cooldown: 90,
                    bounty: 90,
                    armor: 4,
                    scale: 1.6,
                    color: "#92400e",
                    aoe: 60,
                    visual: "club",
                },
                necromancer: {
                    name: "Necromancer",
                    hp: 160,
                    dmg: 20,
                    range: 240,
                    speed: 1.1,
                    cooldown: 120,
                    bounty: 60,
                    armor: 2,
                    ranged: true,
                    projectile: "skull",
                    summon: true,
                    scale: 1.1,
                    color: "#a855f7",
                    visual: "mage",
                },
                skeleton: {
                    name: "Skeleton",
                    hp: 45,
                    dmg: 10,
                    range: 40,
                    speed: 1.5,
                    cooldown: 60,
                    bounty: 2,
                    armor: 0,
                    scale: 0.85,
                    color: "#e2e8f0",
                    visual: "sword",
                },
                dragon: {
                    name: "Dragon",
                    hp: 2200,
                    dmg: 70,
                    range: 160,
                    speed: 2.0,
                    cooldown: 70,
                    bounty: 600,
                    armor: 8,
                    scale: 2.2,
                    color: "#b91c1c",
                    flying: true,
                    aoe: 90,
                    boss: true,
                    visual: "dragon",
                },
            };

            const BUILDING_TYPES = {
                castle: {
                    name: "Castle",
                    hp: 2000,
                    width: 160,
                    height: 140,
                    cost: {},
                    desc: "Your stronghold. Generates +1 gold, +0.5 iron, and +0.5 crystal per sec.",
                    income: { g: 1, i: 0.5, c: 0.5 },
                },
                mine: {
                    name: "Resource Mine",
                    hp: 300,
                    width: 100,
                    height: 80,
                    cost: { g: 50 },
                    desc: "Generates +3 gold/sec and +1 iron/sec.",
                    income: { g: 3, i: 1 },
                    buildTime: 120,
                },
                barracks: {
                    name: "Barracks",
                    hp: 450,
                    width: 120,
                    height: 90,
                    cost: { g: 75 },
                    desc: "Unlocks advanced melee (Swordsman, Spearman, Knight).",
                    unlock: ["swordsman", "spearman", "knight"],
                    buildTime: 180,
                },
                tower: {
                    name: "Guard Tower",
                    hp: 350,
                    width: 60,
                    height: 160,
                    cost: { g: 60 },
                    desc: "Automatically fires arrows at enemies.",
                    dmg: 18,
                    range: 350,
                    cooldown: 40,
                    buildTime: 150,
                },
                wall: {
                    name: "Fortified Wall",
                    hp: 1000,
                    width: 50,
                    height: 100,
                    cost: { g: 40 },
                    desc: "Blocks enemy movement. High health/armor.",
                    armor: 6,
                    buildTime: 90,
                },
                academy: {
                    name: "Academy",
                    hp: 400,
                    width: 110,
                    height: 100,
                    cost: { g: 120, c: 20 },
                    desc: "Unlocks Magic units (Mage, Cleric) and Siege.",
                    unlock: ["mage", "catapult", "cleric"],
                    buildTime: 200,
                },
                archery: {
                    name: "Archery Range",
                    hp: 350,
                    width: 110,
                    height: 85,
                    cost: { g: 60 },
                    desc: "Unlocks Crossbowmen. Enhances Crossbow damage & range after construction.",
                    unlock: ["crossbow"],
                    buildTime: 160,
                },
                obelisk: {
                    name: "Mana Obelisk",
                    hp: 250,
                    width: 60,
                    height: 130,
                    cost: { g: 100, c: 50 },
                    desc: "Boosts Mana Regeneration globally.",
                    income: { mana: 0.05 },
                    buildTime: 150,
                },
                forge: {
                    name: "War Forge",
                    hp: 380,
                    width: 110,
                    height: 90,
                    cost: { g: 80, i: 20 },
                    desc: "Enhances melee unit attack damage by +25% per Forge built.",
                    buildTime: 170,
                },
            };

            const TECH_TREE = [
                {
                    id: "forged_blades",
                    name: "Forged Blades",
                    cost: 150,
                    desc: "+20% melee damage",
                    type: "damage",
                    val: 0.2,
                    applies: "melee",
                },
                {
                    id: "reinforced_armor",
                    name: "Steel Plating",
                    cost: 150,
                    desc: "+15% unit HP",
                    type: "hp",
                    val: 0.15,
                },
                {
                    id: "fletching",
                    name: "Elven Fletching",
                    cost: 120,
                    desc: "+25% arrow range",
                    type: "range",
                    val: 0.25,
                    applies: "ranged",
                },
                {
                    id: "alchemy",
                    name: "Pyromancy",
                    cost: 200,
                    desc: "+30% fireball/meteor damage",
                    type: "damage",
                    val: 0.3,
                    applies: "magic",
                },
                {
                    id: "husbandry",
                    name: "Husbandry",
                    cost: 180,
                    desc: "+15% unit movement speed",
                    type: "speed",
                    val: 0.15,
                },
                {
                    id: "masonry",
                    name: "Masonry",
                    cost: 120,
                    desc: "+25% building HP",
                    type: "bldg_hp",
                    val: 0.25,
                },
                {
                    id: "banking",
                    name: "Taxation",
                    cost: 200,
                    desc: "+20% gold income from all sources",
                    type: "income",
                    val: 0.2,
                },
                {
                    id: "ley_lines",
                    name: "Ley Line Tapping",
                    cost: 250,
                    desc: "+50 Max Mana & +50% Mana Regen",
                    type: "mana",
                    val: 50,
                },
                {
                    id: "healing_touch",
                    name: "Divine Grace",
                    cost: 150,
                    desc: "+30% heal amount (Units & Spells)",
                    type: "heal",
                    val: 0.3,
                },
                {
                    id: "recruitment",
                    name: "Conscription",
                    cost: 120,
                    desc: "+5 maximum population",
                    type: "pop",
                    val: 5,
                },
                {
                    id: "fortified_walls",
                    name: "Titanium Walls",
                    cost: 140,
                    desc: "+10 Wall armor rating",
                    type: "wall_armor",
                    val: 10,
                },
                {
                    id: "quick_reload",
                    name: "Rapid Fire",
                    cost: 160,
                    desc: "Reduces attack cooldown by 15%",
                    type: "cooldown",
                    val: -0.15,
                },
                {
                    id: "crystal_focus",
                    name: "Crystal Resonance",
                    cost: 300,
                    desc: "Increases Crystal Income by 1/sec",
                    type: "crystal_inc",
                    val: 1,
                },
            ];

            const LEVELS = [
                {
                    name: "The Frontier",
                    ground: "#143d26",
                    sky: "#0f172a",
                    weather: "none",
                    waves: [
                        { time: 10, enemies: [{ t: "rabble", c: 6 }] },
                        { time: 35, enemies: [{ t: "rabble", c: 10 }] },
                        {
                            time: 70,
                            enemies: [
                                { t: "rabble", c: 12 },
                                { t: "marauder", c: 4 },
                            ],
                        },
                    ],
                    startGold: 200,
                    reward: 50,
                },
                {
                    name: "Bandit Camp",
                    ground: "#214a1b",
                    sky: "#1e1b4b",
                    weather: "none",
                    waves: [
                        { time: 10, enemies: [{ t: "rabble", c: 10 }] },
                        {
                            time: 40,
                            enemies: [
                                { t: "marauder", c: 6 },
                                { t: "rabble", c: 5 },
                            ],
                        },
                        {
                            time: 80,
                            enemies: [
                                { t: "marauder", c: 10 },
                                { t: "berserker", c: 3 },
                            ],
                        },
                        {
                            time: 120,
                            enemies: [
                                { t: "rabble", c: 15 },
                                { t: "berserker", c: 6 },
                            ],
                        },
                    ],
                    startGold: 250,
                    reward: 80,
                },
                {
                    name: "Shield Wall",
                    ground: "#2b4d1d",
                    sky: "#172554",
                    weather: "rain",
                    waves: [
                        { time: 15, enemies: [{ t: "marauder", c: 8 }] },
                        {
                            time: 50,
                            enemies: [
                                { t: "shieldman", c: 6 },
                                { t: "marauder", c: 6 },
                            ],
                        },
                        {
                            time: 95,
                            enemies: [
                                { t: "shieldman", c: 10 },
                                { t: "archer", c: 5 },
                            ],
                        },
                        {
                            time: 140,
                            enemies: [
                                { t: "shieldman", c: 12 },
                                { t: "berserker", c: 8 },
                                { t: "archer", c: 8 },
                            ],
                        },
                    ],
                    startGold: 280,
                    reward: 120,
                },
                {
                    name: "Rain of Arrows",
                    ground: "#345920",
                    sky: "#2e1065",
                    weather: "rain",
                    waves: [
                        {
                            time: 15,
                            enemies: [
                                { t: "archer", c: 8 },
                                { t: "shieldman", c: 3 },
                            ],
                        },
                        {
                            time: 50,
                            enemies: [
                                { t: "archer", c: 12 },
                                { t: "marauder", c: 10 },
                            ],
                        },
                        {
                            time: 90,
                            enemies: [
                                { t: "archer", c: 18 },
                                { t: "shieldman", c: 10 },
                            ],
                        },
                        {
                            time: 140,
                            enemies: [
                                { t: "archer", c: 25 },
                                { t: "berserker", c: 12 },
                                { t: "marauder", c: 12 },
                            ],
                        },
                    ],
                    startGold: 320,
                    reward: 160,
                },
                {
                    name: "Tribal Magic",
                    ground: "#2c6213",
                    sky: "#022c22",
                    weather: "none",
                    waves: [
                        {
                            time: 15,
                            enemies: [
                                { t: "shaman", c: 4 },
                                { t: "rabble", c: 15 },
                            ],
                        },
                        {
                            time: 55,
                            enemies: [
                                { t: "shaman", c: 5 },
                                { t: "marauder", c: 12 },
                            ],
                        },
                        {
                            time: 100,
                            enemies: [
                                { t: "shaman", c: 6 },
                                { t: "ogre", c: 2 },
                                { t: "shieldman", c: 8 },
                            ],
                        },
                        {
                            time: 150,
                            enemies: [
                                { t: "shaman", c: 8 },
                                { t: "ogre", c: 3 },
                                { t: "berserker", c: 12 },
                            ],
                        },
                    ],
                    startGold: 380,
                    reward: 200,
                },
                {
                    name: "Ogre March",
                    ground: "#45413c",
                    sky: "#3b1703",
                    weather: "snow",
                    waves: [
                        {
                            time: 20,
                            enemies: [
                                { t: "ogre", c: 3 },
                                { t: "rabble", c: 12 },
                            ],
                        },
                        {
                            time: 65,
                            enemies: [
                                { t: "ogre", c: 4 },
                                { t: "archer", c: 10 },
                            ],
                        },
                        {
                            time: 110,
                            enemies: [
                                { t: "ogre", c: 5 },
                                { t: "berserker", c: 12 },
                            ],
                        },
                        {
                            time: 160,
                            enemies: [
                                { t: "ogre", c: 8 },
                                { t: "shaman", c: 5 },
                                { t: "shieldman", c: 15 },
                            ],
                        },
                    ],
                    startGold: 480,
                    reward: 250,
                },
                {
                    name: "The Horde",
                    ground: "#5c280b",
                    sky: "#18181b",
                    weather: "snow",
                    waves: [
                        { time: 10, enemies: [{ t: "rabble", c: 30 }] },
                        {
                            time: 50,
                            enemies: [
                                { t: "marauder", c: 25 },
                                { t: "archer", c: 12 },
                            ],
                        },
                        {
                            time: 100,
                            enemies: [
                                { t: "shieldman", c: 20 },
                                { t: "berserker", c: 20 },
                            ],
                        },
                        {
                            time: 160,
                            enemies: [
                                { t: "ogre", c: 6 },
                                { t: "necromancer", c: 4 },
                                { t: "archer", c: 18 },
                            ],
                        },
                        {
                            time: 220,
                            enemies: [
                                { t: "necromancer", c: 6 },
                                { t: "ogre", c: 8 },
                                { t: "berserker", c: 25 },
                            ],
                        },
                    ],
                    startGold: 600,
                    reward: 350,
                },
                {
                    name: "Dragon Flight",
                    ground: "#3b0606",
                    sky: "#000000",
                    weather: "rain",
                    waves: [
                        {
                            time: 20,
                            enemies: [
                                { t: "dragon", c: 1 },
                                { t: "marauder", c: 12 },
                            ],
                        },
                        {
                            time: 70,
                            enemies: [
                                { t: "dragon", c: 1 },
                                { t: "ogre", c: 6 },
                                { t: "shaman", c: 6 },
                            ],
                        },
                        {
                            time: 130,
                            enemies: [
                                { t: "dragon", c: 2 },
                                { t: "necromancer", c: 5 },
                                { t: "shieldman", c: 20 },
                            ],
                        },
                        {
                            time: 200,
                            enemies: [
                                { t: "dragon", c: 4 },
                                { t: "ogre", c: 12 },
                                { t: "necromancer", c: 8 },
                                { t: "berserker", c: 30 },
                            ],
                        },
                    ],
                    startGold: 900,
                    reward: 600,
                },
            ];

            // --- UTILS ---
