// --- DOM lookup cache ---
// Every element the game reads is created once — static markup in index.html
// or generated by renderActionBar() before the Game is constructed — and is
// never replaced (overlays set innerHTML on themselves, which keeps the node
// reference valid). So a single getElementById per id is safe, and this avoids
// re-querying the DOM every frame from updateUI()/drawMinimap() and once per
// unit per frame from particleQuality().
//
// Returns null for an absent id (cached), exactly like getElementById — callers
// such as the build-button loop legitimately look up ids with no element
// (e.g. the castle has no build button) and guard on the null themselves.
const cache = new Map();

export function el(id) {
    let node = cache.get(id);
    if (node === undefined) {
        node = document.getElementById(id);
        cache.set(id, node);
    }
    return node;
}

// --- Write-if-changed (anti-lag) ---
// updateUI() runs every frame; assigning innerText/innerHTML — even the same
// value — replaces child nodes and invalidates style/layout (innerHTML also
// re-parses). These remember the last value written on the node itself and
// skip identical writes. Only use them for nodes no other code writes to,
// or the remembered value goes stale.
export function setText(node, v) {
    const s = String(v);
    if (node._txt !== s) {
        node._txt = s;
        node.innerText = s;
    }
}

export function setHTML(node, html) {
    if (node._html !== html) {
        node._html = html;
        node.innerHTML = html;
    }
}
