// --- DOM lookup cache ---
// Every element the game reads is created once — static markup in index.html
// or generated by renderActionBar() before the Game is constructed — and is
// never replaced (overlays set innerHTML on themselves, which keeps the node
// reference valid). So a single getElementById per id is safe, and this avoids
// re-querying the DOM every frame from updateUI()/drawMinimap() and once per
// unit per frame from particleQuality().
//
// Returns null for an absent id (cached), exactly like getElementById — callers
// such as the build-button loop legitimately look up ids with no element
// (e.g. the castle has no build button) and guard on the null themselves.
const cache = new Map();

export function el(id) {
    let node = cache.get(id);
    if (node === undefined) {
        node = document.getElementById(id);
        cache.set(id, node);
    }
    return node;
}
